// Symptom Action Types

export const ADD_SYMPTOM = "ADD_SYMPTOM";
export const REMOVE_SYMPTOM = "REMOVE_SYMPTOM";
export const ADD_STRAIN_TO_USER_SAVED = "ADD_STRAIN_TO_USER_SAVED";
export const REMOVE_STRAIN_FROM_USER_SAVED = "REMOVE_STRAIN_FROM_USER_SAVED";
export const ADD_LOG_TO_DOSAGE_LOGS = "ADD_LOG_TO_DOSAGE_LOGS";